// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO_HGoEMJLGMeKPetAe9AJ9nL0MUyNx_I',
    appId: '1:637297847938:web:d27d5fe38041baf390ce9b',
    messagingSenderId: '637297847938',
    projectId: 'lati-games-30041',
    authDomain: 'lati-games-30041.firebaseapp.com',
    storageBucket: 'lati-games-30041.appspot.com',
    measurementId: 'G-H52DC3NRJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrf2XW5Mv8jbvyTNf4KS3HHrVVNJTWbY',
    appId: '1:637297847938:android:ffa41600803aecb290ce9b',
    messagingSenderId: '637297847938',
    projectId: 'lati-games-30041',
    storageBucket: 'lati-games-30041.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO_HGoEMJLGMeKPetAe9AJ9nL0MUyNx_I',
    appId: '1:637297847938:web:f39df0d42c7b520790ce9b',
    messagingSenderId: '637297847938',
    projectId: 'lati-games-30041',
    authDomain: 'lati-games-30041.firebaseapp.com',
    storageBucket: 'lati-games-30041.appspot.com',
    measurementId: 'G-B7X2RFWKH8',
  );
}
